<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lab1_1.css" type="text/css"?>
<!DOCTYPE company[
<!ELEMENT company (companyName,employee+)>
<!ELEMENT companyName (#PCDATA)>
<!ELEMENT employee (name,phones,addresses,email)>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phones Type ID #REQUIRED>
<!ATTLIST phone Mobile IDREF #IMPLIED>
<!ATTLIST phone Home IDREF #IMPLIED>
<!ATTLIST phone Work IDREF #IMPLIED>
<!ELEMENT addresses (address+)>
<!ELEMENT address (street,buildingNumber,region,city,country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT buildingNumber (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email email ID #REQUIRED>
]>

<company>
    <companyName>ITI</companyName>
    <employee>
        <name>
            <fname>Hassan</fname>
            <lname>Tawfic</lname>
        </name>
        <phones Type="a1">
            <phone Mobile="a1">+01000000232</phone>
            <phone Home="a1">+0346546546654</phone>
            <phone Work="a1">+01000000232</phone>
        </phones>
        <addresses>
            <address>
                <street>
                    El-Sheikh Muhamed Abdou
                </street>
                <buildingNumber>21</buildingNumber>
                <region>Bahary</region>
                <city>Alexandria</city>
                <country>Egypt</country>
            </address>
            <address>
                <street>other street</street>
                <buildingNumber>#</buildingNumber>
                <region>other</region>
                <city>Alexandria</city>
                <country>Egypt</country>
            </address>
        </addresses>
        <email email="b1">hatawfic@gmail.com</email>

    </employee>
</company>